[package]
name = "aalias"
version = "0.1.0"
authors = ["Federico Vitale <fedevitale99@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simple-storage = "0.0.2"
clap = "3.0.0-beta.2"
